CLAIM_TABLE = {
    "main_table": "claim",
    "history_table": "claim_history",
    "primary_key": "claim_id",
    "columns": [
        "claim_id",
        "patient_id",
        "provider_id",
        "visit_type",
        "total_cost",
        "coverage_type",
        "date_of_service",
        "claim_date",
        "billed",
        "last_modified_date",
    ],
    "main_table_column_data_type": {
        "claim_id": "TEXT PRIMARY KEY",
        "patient_id": "TEXT",
        "provider_id": "TEXT",
        "visit_type": "TEXT",
        "total_cost": "REAL",
        "coverage_type": "TEXT",
        "date_of_service": "DATETIME",
        "claim_date": "DATETIME",
        "billed": "REAL",
        "last_modified_date": "DATETIME",
    },
    "history_table_column_data_type": {
        "claim_id": "TEXT",
        "patient_id": "TEXT",
        "provider_id": "TEXT",
        "visit_type": "TEXT",
        "total_cost": "REAL",
        "coverage_type": "TEXT",
        "date_of_service": "DATETIME",
        "claim_date": "DATETIME",
        "billed": "REAL",
        "last_modified_date": "DATETIME",
    },
    "data_type": {
        "claim_id": str,
        "patient_id": str,
        "provider_id": str,
        "visit_type": str,
        "total_cost": str,
        "coverage_type": str,
        "date_of_service": str,
        "claim_date": str,
        "billed": str,
        "last_modified_date": str,
    },
}

PATIENT_TABLE = {
    "main_table": "patient",
    "history_table": "patient_history",
    "primary_key": "patient_id",
    "columns": [
        "patient_id",
        "fname",
        "lname",
        "date_of_birth",
        "address",
        "city",
        "state",
        "zipcode",
        "date_of_residence",
        "last_modified_date",
    ],
    "main_table_column_data_type": {
        "patient_id": "TEXT PRIMARY KEY",
        "fname": "TEXT",
        "lname": "TEXT",
        "date_of_birth": "DATETIME",
        "address": "TEXT",
        "city": "TEXT",
        "state": "TEXT",
        "zipcode": "INTEGER",
        "date_of_residence": "DATETIME",
        "last_modified_date": "DATETIME",
    },
    "history_table_column_data_type": {
        "patient_id": "TEXT",
        "fname": "TEXT",
        "lname": "TEXT",
        "date_of_birth": "DATETIME",
        "address": "TEXT",
        "city": "TEXT",
        "state": "TEXT",
        "zipcode": "INTEGER",
        "date_of_residence": "DATETIME",
        "last_modified_date": "DATETIME",
    },
    "data_type": {
        "patient_id": str,
        "fname": str,
        "lname": str,
        "date_of_birth": str,
        "address": str,
        "city": str,
        "state": str,
        "zipcode": str,
        "date_of_residence": str,
        "last_modified_date": str,
    },
}

PROVIDER_TABLE = {
    "main_table": "provider",
    "history_table": "provider_history",
    "primary_key": "provider_id",
    "columns": [
        "provider_id",
        "fname",
        "lname",
        "facility_name",
        "address",
        "city",
        "state",
        "zipcode",
        "specialty_code",
        "start_date",
    ],
    "main_table_column_data_type": {
        "provider_id": "TEXT PRIMARY KEY",
        "fname": "TEXT",
        "lname": "TEXT",
        "facility_name": "TEXT",
        "address": "TEXT",
        "city": "TEXT",
        "state": "TEXT",
        "zipcode": "INTEGER",
        "specialty_code": "TEXT",
        "start_date": "TEXT",
    },
    "history_table_column_data_type": {
        "provider_id": "TEXT",
        "fname": "TEXT",
        "lname": "TEXT",
        "facility_name": "TEXT",
        "address": "TEXT",
        "city": "TEXT",
        "state": "TEXT",
        "zipcode": "INTEGER",
        "specialty_code": "TEXT",
        "start_date": "TEXT",
    },
    "data_type": {
        "provider_id": str,
        "fname": str,
        "lname": str,
        "facility_name": str,
        "address": str,
        "city": str,
        "state": str,
        "zipcode": str,
        "specialty_code": str,
        "start_date": str,
    },
}
